### ISSUE TITLE
Joybox.io homepage main-navigation menu doesn't scroll 

### ISSUE THREAD

**Issue by estsauver** [rubymotion-community/Joybox#17]
Hi All, 

The left menu on joybox.io doesn't scroll and all of the options aren't visible in the sidebar on an 11'" macbook air. I didn't see where in the stylesheet that class was defined, but I thought y'all would appreciate a heads up.

This project is really neat, as an aside.

~Earl

**Comment by NSCoder** [comment]
Hey Earl!

Thanks for the report! The website is located in this repo:https://github.com/CurveBeryl/Joybox-Documentation, its a octopress project. You can find the stylesheets in the SASS folder :)

Please let me know if you need more info! :D

**Comment by kfatehi** [comment]
@CurveBeryl I actually noticed this too, forked, and tried to go in and fix (branch: master).
I did a `rake generate` and then served the public directory but the page does not behave the same as that which is live on http://joybox.io

![screen shot 2013-07-27 at 4 37 14 pm](https://f.cloud.github.com/assets/175305/867627/d7bb89ce-f715-11e2-98ca-533b1ec5ed98.png)

Since I'd have to edit seemingly working code to try to get it to behave like the published site, let alone to fix #17 I've decided not to try to fix this for now

**Comment by NSCoder** [comment]
Hello Keyvan:

First of all thank you for looking into this! May be is a resolution problem (Here looks correct), the patch that fix this one is coming on tuesday.

Thanks again!

JK

**Comment by NSCoder** [comment]
Fixed with the new website! Hope you like it :)
