### ISSUE TITLE
Random error when starting the game in the simulator

### ISSUE THREAD

**Issue by nside** [rubymotion-community/Joybox#29]
I get these errors randomly when running a game in the simulator. Just re-running rake fixes it.

(main)> Stack dump:
0.  Running pass 'X86 Machine Code Emitter' on function '@glgRunProcessor5'
((null))> rake aborted!

main)> Stack dump:
0.  Running pass 'X86 Machine Code Emitter' on function '@gleLLVMVecPrimMultiRender1'
((null))> rake aborted!

**Comment by NSCoder** [comment]
Hello Denis!

Thanks for the report, but sadly this happen because a symbol Collision between the REPL module and OpenGL Framework, because of this it only happens on the simulator. On the other side Laurent already report the bug to Apple:

https://groups.google.com/forum/?fromgroups#!searchin/rubymotion/X86$20Machine$20Code$20Emitter/rubymotion/Qra3YntsACU/4RYdAimtvY4J

Sorry about that but there is nothing I can do to fix it :(

JK

**Comment by nside** [comment]
Interesting
